// Generated by CoffeeScript 1.6.3
/*
** Annotator 1.2.6-dev-2718179
** https://github.com/okfn/annotator/
**
** Copyright 2012 Aron Carroll, Rufus Pollock, and Nick Stenning.
** Dual licensed under the MIT and GPLv3 licenses.
** https://github.com/okfn/annotator/blob/master/LICENSE
**
** Built at: 2014-01-22 14:40:53Z
*/



/*
//
*/

// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Annotator.Plugin.PDF = (function(_super) {
    __extends(PDF, _super);

    function PDF() {
      _ref = PDF.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PDF.prototype.pluginInit = function() {
      if (!this.annotator.plugins.DomTextMapper) {
        throw "The PDF Annotator plugin requires the DomTextMapper plugin.";
      }
      return this.annotator.documentAccessStrategies.unshift({
        name: "PDF.js",
        applicable: PDFTextMapper.applicable,
        get: function() {
          return new PDFTextMapper();
        }
      });
    };

    return PDF;

  })(Annotator.Plugin);

}).call(this);

//
//@ sourceMappingURL=annotator.pdf.map